name: Build with Java 21
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn package
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: eHelper-Java21
          path: target/eHelper-*.jar
